   
                              null                                                           equ    0
                              NULL                                                       equ     0
                              true                                                          Equ      1
                              TRUE                                                     Equ     1
                              True                                                         Equ     1
                              false                                                        equ      0
                              FALSE                                                    equ     0
                              False                                                       equ    0
                              Null                                                          equ     0
;==============================  


