   
                              null                                                           equ    0
                              NULL                                                       equ     0
                              true                                                          Equ      1
                              TRUE                                                     Equ     1
                              True                                                         Equ     1
                              false                                                        equ      0
                              FALSE                                                    equ     0
                              False                                                       equ    0
                              Null                                                          equ     0
;==============================  
PROGRAM_STRUCT     STRUC

   uLEN                  DD      null
    uHIG                  DD    null 
    uDESK_HDC     DD   null
    uWIN_HDC                       DD   Null
    uCOMP_HDC                   DD   Null
   uComp_BITMAP                      DD    null
    
PROGRAM_STRUCT     ENDS                              


